# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  debug_build:
    name: 'Debug Build'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v6
      # Runs a single command using the runners shell
      - name: Build
        run: emcc maze.cpp mazeweb.cpp -o mazeweb.js -g4 -s NO_EXIT_RUNTIME=1
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: mazeweb_debug.js # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: mazeweb.js
          
  release_build:
    name: 'Release Build'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v6
      # Runs a single command using the runners shell
      - name: Build
        run: emcc maze.cpp mazeweb.cpp -o mazeweb.js -O2 -s NO_EXIT_RUNTIME=1
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: mazeweb.js # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: mazeweb.js          
